### ISSUE TITLE
don't install magpurify2

### ISSUE THREAD

**Issue by nashanghenzan** [apcamargo/magpurify2#2]
pip and conda don't find package of magpurify2

**Comment by apcamargo** [comment]
The package is not currently available in pip. You can install it manually:

```
git clone https://github.com/apcamargo/magpurify2.git
cd magpurify2
python setup.py
```

**Comment by nashanghenzan** [comment]
> The package is not currently available in pip. You can install it manually:
> 
> ```
> git clone https://github.com/apcamargo/magpurify2.git
> cd magpurify2
> python setup.py
> ```

still don't install magpurify2 because the cargo problem, so i decide to wait the bioconda package
